import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import Footer from "./comps/Footer/Footer";
import MobileNavModal from "./comps/MobileNavModal/MobileNavModal";

const rubik = Rubik({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        {children}
        <Footer />

        <div
          style={{
            textAlign: "center",
            marginTop: "20px",
            marginBottom: "20px",
          }}
        >
          Challenge by{" "}
          <a href="https://www.frontendmentor.io">Frontend Mentor</a>. Code by{" "}
          <a href="https://www.frontendmentor.io/profile/DinosMpo">DinosMpo</a>
        </div>
      </body>
    </html>
  );
}
